### ISSUE TITLE
ping一个不通的ip 会     [[NSRunLoop currentRunLoop]  runMode:NSDefaultRunLoopMode beforeDate:[NSDate distantFuture]]; 死循环

### ISSUE THREAD

**Issue by whzooo** [Lede-Inc/LDNetDiagnoService_IOS#34]

**Comment by whzooo** [comment]
[[NSRunLoop currentRunLoop]  runMode:NSDefaultRunLoopMode beforeDate:[NSDate distantFuture]];
会停在这里 不忘下走了

**Comment by wv-y** [comment]
我也遇到这个问题了，请问有什么解决办法吗？

**Comment by wv-y** [comment]
我给beforeDate设置为明确的过期时间：[NSDate dateWithTimeIntervalSinceNow:(MAXCOUNT_PING + 1) * 3]，来避免卡死，但是根本原因没找到。
