### ISSUE TITLE
IPv6网络中，Demo的编译配置选择release，运行时必现崩溃

### ISSUE THREAD

**Issue by dawn1389ims** [Lede-Inc/LDNetDiagnoService_IOS#8]
![netdiagnoipv6](https://cloud.githubusercontent.com/assets/5118002/18857720/db19ca90-8498-11e6-8d50-778e35385d70.png)

**Comment by dawn1389ims** [comment]
原因是IPv6下 sockaddr_in6 长度28，而代码中声明sockaddr 长度16，导致recvfrom函数执行时向sockaddr填充超过其长度的数据，栈异常。

解决办法需要参照https://github.com/WeMobileDev/article/blob/master/IPv6%20socket%E7%BC%96%E7%A8%8B.md#%E6%9B%B4%E5%8A%A0%E8%8A%82%E7%9C%81%E7%A9%BA%E9%97%B4%E7%9A%84%E6%96%B9%E6%A1%88
的方案

**Comment by LL1992** [comment]
请问这个bug要修改哪里的代码，谢谢了

**Comment by dawn1389ims** [comment]
问题原因：
原因是IPv6下 sockaddr_in6 长度28，而代码中声明sockaddr 长度16，导致recvfrom函数执行时向sockaddr填充超过其长度的数据，栈异常。
解决办法：
参照https://github.com/WeMobileDev/article/blob/master/IPv6%20socket%E7%BC%96%E7%A8%8B.md#%E6%9B%B4%E5%8A%A0%E8%8A%82%E7%9C%81%E7%A9%BA%E9%97%B4%E7%9A%84%E6%96%B9%E6%A1%88 https://github.com/WeMobileDev/article/blob/master/IPv6%20socket%E7%BC%96%E7%A8%8B.md#%E6%9B%B4%E5%8A%A0%E8%8A%82%E7%9C%81%E7%A9%BA%E9%97%B4%E7%9A%84%E6%96%B9%E6%A1%88
的方案:
union sockaddr_union {
        struct sockaddr     sa;     //16
        struct sockaddr_in  in4;    //16
        struct sockaddr_in6 in6;    //28
    } fromAddr;

**Comment by LL1992** [comment]
你好，
我在LDNetTraceRoute.m中 添加了
union sockaddr_union {
        struct sockaddr     sa;     //16
        struct sockaddr_in  in4;    //16
        struct sockaddr_in6 in6;    //28
    } fromAddr;

注释了原代码中的  //    struct sockaddr fromAddr;
然后修改了这两个判断条件：
                    //将“二进制整数” －> “点分十进制，获取hostAddress和hostName
                    if (fromAddr.sa.sa_family == AF_INET) {
                    // code
                    else if (fromAddr.sa.sa_family == AF_INET6) {
                   //  code
                    }
这样下来，ipv6网络下不会崩溃了。
换到ipv4也能正常运行。
不知道这样改的对不对。

**Comment by dawn1389ims** [comment]
导致崩溃的地方其实是 recvfrom(recv_sock, buf, 100, 0, &fromAddr.sa, &n)
这里改对就可以了的。

**Comment by LL1992** [comment]
好的，谢谢你了
